id: I448B983E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:52:36+00:00'
last_modified: '2022-06-08T14:23:29.118705+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30475
  title: ཁུ་སིམ་ཁད་ཀྱིས་དཀྲོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '5346':
      image_group_id: I1KG22919
      title: ''
      total_pages: 244
      order: 1
      base_file: 5346.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
