id: P010545
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30475
  title: ཁུ་སིམ་ཁད་ཀྱིས་དཀྲོག
  author: ''
  volumes:
    91af2a3d9e67440099cce351fb3e1af8:
      image_group_id: I1KG22919
      title: ''
      volume_number: 1
      total_pages: 244
      base_file: v001.txt
